falcosecurity/plugin-sdk-cpp

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
/area build
> Added PR template.

- CMakeLists.txt
- Makefile
- include/plugin_info.h
```
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
```
> /kind bug
/kind cleanup
> /kind design
/area build
> /area tests
Fixes #
```release-note
NONE
```
> build: added a Makefile to download plugin_info from falcosecurity/libs

- README.md
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
> /kind bug
/kind cleanup
> /kind design
/area build
> /area tests
Fixes #
```release-note
NONE
```
> chore(readme): updated links pointing to falco doc.

- OWNERS
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
> /kind bug
> /kind design
/area build
> /area tests
Fixes #
```release-note
NONE
```
> documentation: added fededp to owners.

- OWNERS
Supersedes #7, see: https://github.com/falcosecurity/plugin-sdk-cpp/pull/7#issuecomment-1189976110.
```release-note
NONE
```
> update(OWNERS): move fntlnz to emeritus_approvers

- include/falcosecurity/event_reader.h
- include/falcosecurity/internal/conversions.h
- include/falcosecurity/internal/plugin_mixin_extraction.h
kind bug
/kind cleanup
```release-note
NONW
```
> fix: solve minor bugs and issues

- examples/plugin_extract/plugin.cpp
- examples/plugin_source/plugin.cpp
- examples/syscall_async/plugin.cpp
- examples/syscall_extract/plugin.cpp
- examples/syscall_parse/plugin.cpp
- include/falcosecurity/internal/plugin_mixin_common.h
- include/falcosecurity/internal/plugin_mixin_sourcing.h
- include/falcosecurity/internal/symbols_common.h
/kind feature
```release-note
update: support optional `destroy` and `close` methods
```
> update: support optional `destroy` and `close` methods

- examples/syscall_async/plugin.cpp
- include/falcosecurity/async_event_handler.h
- include/falcosecurity/internal/plugin_mixin_async.h
/kind bug
> /kind design
> /area build
> /area tests
Each thread should have its own event writer to push event, and it should not be contended by all the threads the plugin can spawn and that are allowed to send events.
Fixes #
```release-note
```
> update: add async event handler factory 

- examples/syscall_async/plugin.cpp
- include/falcosecurity/async_event_handler.h
- include/falcosecurity/internal/plugin_mixin_async.h
> /kind bug
> /kind design
> /area build
> /area tests
Fixes #
```release-note
```
> update: apply clang format

- Makefile
> /kind bug
> /kind design
/area build
> /area tests
As per PR title. INSTALL_DIR will be customizable.
Fixes #
```release-note
```
> update(Makefile): add install and uninstall targets

- Makefile
- include/falcosecurity/internal/deps/plugin_api.patch
- include/falcosecurity/internal/plugin_mixin_common.h
> /kind bug
> /kind design
> /area build
> /area tests
Fixes #
```release-note
```
> new(make): patch plugin_api.h header include

- include/falcosecurity/types.h
/kind cleanup
The `falcosecurity::logger` API has been improved to always inline methods, to support `const char*` strings, and to avoid segfaults if initialized with no callback.
```release-note
update: make logger more resilient and performant
```
> update: make logger more resilient and performant

- Makefile
- examples/syscall_parse/plugin.cpp
- include/falcosecurity/inputs.h
- include/falcosecurity/internal/deps/plugin_api.h
- include/falcosecurity/internal/deps/plugin_types.h
- include/falcosecurity/internal/plugin_mixin.h
- include/falcosecurity/internal/plugin_mixin_capture_listening.h
- include/falcosecurity/internal/symbols_capture_listening.h
- include/falcosecurity/sdk.h
> /kind bug
> /kind design
> /area build
> /area tests
Fixes #
```release-note
```
> new: add capture_open/capture_close hooks

- .github/workflows/release.yaml
- README.md
/kind bug
Fixes #
```release-note
NONE
```
> chore(ci): fix release job name.

- README.md
- release.md
Fixes #
```release-note
NONE
```
> new(docs): added release file.

- examples/syscall_async/plugin.cpp
- examples/syscall_async/syscall_async_rules.yaml
> /kind bug
> /kind design
> /area build
> /area tests
Better documentation needed for async syscall processing.
Fixes #
No 
```release-note
NONE
```
> add extract code sample to syscall_async documentation

- examples/syscall_subtables/plugin.cpp
> /kind bug
> /kind design
> /area build
> /area tests
Need an example for cgroups access via API
Fixes #
Please approve
```release-note
NONE
```
> add example for cgroup access via plugin API  

- include/falcosecurity/internal/hacks.h
/kind bug
Fixes #
```release-note
NONE
```
> fix(include): use proper `__forceinline` flag for msvc.

- include/falcosecurity/events/decoders.h
- include/falcosecurity/events/encoders.h
/kind bug
Fixes #
```release-note
NONE
```
> fix(include): avoid UB in event encoders/decoders.

- Makefile
- examples/syscall_parse/plugin.cpp
- include/falcosecurity/internal/deps/plugin_api.h
- include/falcosecurity/internal/deps/plugin_types.h
- include/falcosecurity/internal/plugin_mixin_common.h
- include/falcosecurity/internal/symbols_common.h
> /kind bug
> /kind design
/kind feature
/area build
> /area tests
Fixes #
```release-note
feat: support for `get_required_event_schema_version()`
```
> feat: support for `get_required_event_schema_version()`
